### ISSUE TITLE
RX - Editing frequency issue

### ISSUE THREAD

**Issue by WebD00D** [WebD00D/maya-web-app#157]
If you have set the frequency field, for example to "2 times per day".. and have added those 2 times...

If you want to edit, and make it only one time per day, the field for the second time is hidden, so it can't clear out the value. So when you save, it still has that second time in the payload.

**Comment by eggfountain** [comment]
Hi Christian,

 

I had another white screen incident.  I made a sleep entry  and I didn’t enter the time correctly.  Went back into the  Dashboard ==> make an Entry ==>Sleep;  then select the entry from the right side and select Edit Entry.

Results in a blank screen.  I am able to duplicate this every time. 

 

 

 

 

Sent: Sunday, December 29, 2019 3:30 PM
To: WebD00D/maya-web-app <maya-web-app@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: [WebD00D/maya-web-app] RX - Editing frequency issue (#157)

 

If you have set the frequency field, for example to "2 times per day".. and have added those 2 times...

If you want to edit, and make it only one time per day, the field for the second time is hidden, so it can't clear out the value. So when you save, it still has that second time in the payload.
